Socio.searchByCognome=\
    select s from Socio s \
    where s.cognome like :cognome%

socio.selectByAttivita=\
    select s from Socio s \
    inner join s.abbonamento abb \
    inner join abb.attivita att \
    where att.id = :id

socio.search=\
    select distinct s from Socio s \
    left join s.abbonamento abb \
    left join abb.attivita att \
    where lower(s.nome) like :nome \
    and lower(s.cognome) like :cognome \
    and (:attivitaId is null or att.id = :attivitaId)
